version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: youshuren
      POSTGRES_USER: youshuren
      POSTGRES_DB: youshuren

  youshuren:
    image: youshuren:0.1
    ports:
      - "6666:6666"
